name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions: write-all

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  trying:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Convert Markdown into HTML and PDF
      uses: KoharaKazuya/marp-cli-action@v2
      with:
        generate-pdf: true
        generate-html: true
        generate-pptx: true


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./